-- 코드를 입력하세요
SELECT BOOK_ID
    ,  DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM BOOK
WHERE PUBLISHED_DATE BETWEEN STR_TO_DATE('2021-01-01', '%Y-%m-%d') 
AND STR_TO_DATE('2021-12-31', '%Y-%m-%d') -- INDEX 성능을 위해 작성
AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE